// Database schema types for Kysely

import type { ColumnType } from 'kysely';

// Table schemas matching the database structure
export interface MovieTable {
  id: ColumnType<number, never, never>; // Generated always as identity
  title: string;
  year: number | null;
  director: string | null;
  runtime: number | null;
  tmdb_id: number | null;
  tmdb_url: string | null;
  poster_url: string | null;
  letterboxd_url: string | null;
  tmdb_popularity: number | null;
  created_at: ColumnType<Date, never, never>; // Generated by default
  updated_at: ColumnType<Date, never, Date>; // Can be updated manually
}

export interface ScreeningTable {
  id: ColumnType<number, never, never>; // Generated always as identity
  movie_id: number;
  datetime: Date;
  theatre_name: string;
  booking_url: string;
  note: string | null;
  created_at: ColumnType<Date, never, never>; // Generated by default
  updated_at: ColumnType<Date, never, Date>; // Can be updated manually
}

export interface ScrapeRunTable {
  id: ColumnType<number, never, never>; // Generated always as identity
  scraper: string;
  started_at: Date;
  finished_at: Date;
  screening_count: number;
  error: string | null;
  created_at: ColumnType<Date, never, never>; // Generated by default
}

// Review queue for likely-wrong TMDB matches, populated by build-tmdb-review.ts
// and consumed by the /internal-tmdb-review page. One row per flagged movie;
// rows are deleted as they're resolved (fixed or dismissed).
export interface TmdbReviewTable {
  movie_id: number;
  stored_title: string;
  current_tmdb_id: number | null;
  current_title: string | null;
  current_year: number | null;
  current_poster_url: string | null;
  suggested_tmdb_id: number | null;
  suggested_title: string | null;
  suggested_year: number | null;
  suggested_poster_url: string | null;
  suggested_overview: string | null;
  created_at: ColumnType<Date, never, never>; // Generated by default
}

// Database interface combining all tables
export interface Database {
  movie: MovieTable;
  screening: ScreeningTable;
  scrape_run: ScrapeRunTable;
  tmdb_review: TmdbReviewTable;
}
