// Database schema types for Kysely

import type { ColumnType } from 'kysely';

// Table schemas matching the database structure
export interface MovieTable {
  id: ColumnType<number, never, never>; // Generated always as identity
  title: string;
  year: number | null;
  director: string | null;
  runtime: number | null;
  tmdb_id: number | null;
  tmdb_url: string | null;
  poster_url: string | null;
  created_at: ColumnType<Date, never, never>; // Generated by default
  updated_at: ColumnType<Date, never, Date>; // Can be updated manually
}

export interface ScreeningTable {
  id: ColumnType<number, never, never>; // Generated always as identity
  movie_id: number;
  datetime: Date;
  theatre_name: string;
  booking_url: string;
  created_at: ColumnType<Date, never, never>; // Generated by default
  updated_at: ColumnType<Date, never, Date>; // Can be updated manually
}

// Database interface combining all tables
export interface Database {
  movie: MovieTable;
  screening: ScreeningTable;
}
